wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    ports:
     - "8080:80"
    env_file: .env
    volumes:
     - ./wp-content:/var/www/html/wp-content
mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
     - ./database:/var/lib/mysql